id: don-udon
title:
  en: Don Udon
  ru: Don Udon
coords:
  lat: 40.6741008
  lng: -73.9571564
category:
- food
price: $$
address: 634 Park Pl, Brooklyn, NY 11238
external_link: https://www.tiktok.com/t/ZP8gH3PUt
personal: to-do
