id: federal-reserve
title:
  en: Federal Reserve Bank
  ru: Федеральный резерв
coords:
  lat: 40.7074
  lng: -74.0103
category:
- landmarks
address: 33 Liberty St, New York, NY 10045
external_link: ''
personal: visited
price: $$
