id: trinity-church
title:
  en: Trinity Church
  ru: Церковь Тринити
coords:
  lat: 40.7081
  lng: -74.012
category:
- landmarks
address: 89 Broadway, New York, NY 10006
external_link: ''
personal: to-do
price: $$
