id: flushing-meadows-corona-park
title:
  en: Flushing Meadows Corona Park
  ru: Флашинг-Медоус Корона-парк
coords:
  lat: 40.73971
  lng: -73.84079
category:
- parks
address: Grand Central Pkwy, Queens, NY 11368
external_link: ''
personal: to-do
price: free
