id: little-italy
title:
  en: Little Italy
  ru: Литл-Итали
coords: {lat: 40.7191, lng: -73.9973}
category: [landmarks]
time: short
cost: free
transit:
  en: Canal St / Spring St
  ru: Canal St / Spring St
