id: central-park-mall
title:
  en: The Mall
  ru: Аллея The Mall
coords:
  lat: 40.7745
  lng: -73.971
category:
- parks
address: The Mall, Central Park, New York, NY 10022
external_link: ''
personal: to-do
price: $$
