id: golden-manna-bakery
title:
  en: Golden Manna Bakery
  ru: Golden Manna Bakery
coords:
  lat: 40.7145755
  lng: -73.9975494
category:
- food
price: $$
address: 16 Bowery, New York, NY 10013
external_link: https://www.tiktok.com/t/ZP8gHNCvS
personal: to-do
