id: golden-manna-bakery
title:
  en: Golden Manna Bakery
  ru: Golden Manna Bakery
coords:
  lat: 40.7145755
  lng: -73.9975494
category:
- food
tags: []
time: short
cost: paid
price: ''
transit:
  en: Canal St
  ru: Canal St
address: 16 Bowery, New York, NY 10013
external_link: https://www.tiktok.com/t/ZP8gHNCvS
featured: false
personal: want-to-go
