id: xiang-la-hot-pot
title:
  en: Xiang La Hot Pot
  ru: Xiang La Hot Pot
coords:
  lat: 40.7476986
  lng: -73.9873436
category:
- food
price: $$
address: '34 W 32nd St #2F, New York, NY 10001'
external_link: https://www.tiktok.com/t/ZP8gHYhuh
personal: to-do
