id: flatiron-building
title:
  en: Flatiron Building
  ru: Флэтайрон
coords:
  lat: 40.7411
  lng: -73.9897
category:
- landmarks
address: 175 5th Ave, New York, NY 10010
external_link: ''
personal: to-do
price: $$
