id: hay-hay-roasted
title:
  en: Hay Hay Roasted
  ru: Hay Hay Roasted
coords:
  lat: 40.7166048
  lng: -73.9981461
category:
- food
tags: []
time: short
cost: paid
price: ''
transit:
  en: Canal St
  ru: Canal St
address: 81 Mott St, New York, NY 10013
external_link: https://www.tiktok.com/t/ZP8gHy6dX
featured: false
