id: elevated-acre
title:
  en: Elevated Acre
  ru: Elevated Acre
coords:
  lat: 40.704
  lng: -74.007
category:
- hidden-gems
address: 55 Water St, New York, NY 10041
external_link: ''
personal: visited
price: $$
