id: san-matteo-upper-east-side
title:
  en: San Matteo
  ru: San Matteo
coords:
  lat: 40.774651
  lng: -73.9543326
category:
- food
tags: []
time: medium
cost: paid
price: ''
transit:
  en: 86 St / Upper East Side
  ru: 86 St / Upper East Side
address: 1559 2nd Ave, New York, NY 10028
external_link: https://www.tiktok.com/t/ZP8gHbXVB
featured: false
personal: want-to-go
