id: krispy-kreme-times-square
title:
  en: Krispy Kreme (Times Square)
  ru: Krispy Kreme на Таймс-сквер
coords:
  lat: 40.7569
  lng: -73.9863
category:
- food
address: 1601 Broadway, New York, NY 10019
borough: Manhattan
neighborhood: Midtown West
route_types:
- date-night
- easy-stop
- foodie
best_time:
- dinner
- evening
- late-afternoon
- lunch
vibes:
- tasty
best_for:
- couples
external_link: ''
personal: want-to-go
price: $$
