id: krispy-kreme-times-square
title:
  en: Krispy Kreme (Times Square)
  ru: Krispy Kreme на Таймс-сквер
coords:
  lat: 40.7569
  lng: -73.9863
category:
- food
address: 1601 Broadway, New York, NY 10019
external_link: ''
personal: visited
price: $$
