id: lafayette-grand-cafe-bakery
title:
  en: Lafayette Grand Café & Bakery
  ru: Lafayette Grand Café & Bakery
coords:
  lat: 40.7276085
  lng: -73.9937902
category:
- food
price: $$
address: 380 Lafayette St, New York, NY 10003
external_link: https://www.tiktok.com/t/ZP8gHmSRS
personal: to-do
