id: little-italy
title:
  en: Little Italy
  ru: Литл-Итали
coords:
  lat: 40.7191
  lng: -73.9973
category:
- landmarks
address: Mulberry St & Grand St, New York, NY 10013
external_link: ''
personal: visited
price: $$
