id: louis-vuitton-5th-ave
title:
  en: Louis Vuitton (5th Ave)
  ru: Louis Vuitton на 5-й авеню
coords: {lat: 40.7607, lng: -73.9750}
category: [other]
time: short
cost: free
transit:
  en: 5 Av/53 St
  ru: 5 Av/53 St
