id: liberty-bagels-midtown
title:
  en: Liberty Bagels
  ru: Liberty Bagels
coords:
  lat: 40.764
  lng: -73.9778
category:
- food
address: 260 W 35th St, New York, NY 10001
external_link: ''
personal: visited
price: $$
