id: mei-lai-wah
title:
  en: Mei Lai Wah
  ru: Mei Lai Wah
coords:
  lat: 0.0
  lng: 0.0
category:
- food
tags: []
time: short
cost: paid
price: ''
transit:
  en: Canal St
  ru: Canal St
address: 41 Mott St, New York, NY 10013
external_link: https://www.tiktok.com/t/ZP8gHmWwe
featured: false
personal: want-to-go
