id: mei-lai-wah
title:
  en: Mei Lai Wah
  ru: Mei Lai Wah
coords:
  lat: 40.7151859
  lng: -73.9990557
category:
- food
price: $$
address: 41 Mott St, New York, NY 10013
external_link: https://www.tiktok.com/t/ZP8gHmWwe
personal: to-do
