id: mojo-east
title:
  en: Mojo East
  ru: Mojo East
coords:
  lat: 40.7213654
  lng: -73.9888203
category:
- food
price: $$
address: 85 Stanton St, New York, NY 10002
external_link: https://www.tiktok.com/t/ZP8gHM7S7
personal: want-to-go
