id: bronx-zoo
title:
  en: Bronx Zoo
  ru: Бронксский зоопарк
coords:
  lat: 40.8506
  lng: -73.8769
category:
- parks
price: $$
address: 2300 Southern Blvd, Bronx, NY 10460
external_link: ''
personal: to-do
