id: bronx-zoo
title:
  en: Bronx Zoo
  ru: Бронксский зоопарк
coords:
  lat: 40.8506
  lng: -73.8769
category:
- parks
price: $$
address: 2300 Southern Blvd, Bronx, NY 10460
route_types:
- anchor-stop
- family
- kids
- outdoors
- relaxing
- scenic
best_time:
- afternoon
- golden-hour
- morning
vibes:
- photogenic
- slow
best_for:
- families
external_link: ''
personal: want-to-go
