id: syko
title:
  en: Syko
  ru: Syko
coords:
  lat: 40.6603056
  lng: -73.9807222
category:
- food
price: $$
address: 214A Prospect Park W, Brooklyn, NY 11215
external_link: https://www.tiktok.com/t/ZP8gHaxeR
personal: to-do
