id: nathans-famous
title:
  en: Nathan's Famous
  ru: Nathan's Famous
coords:
  lat: 40.5755
  lng: -73.9819
category:
- food
address: 1310 Surf Ave, Brooklyn, NY 11224
borough: Brooklyn
neighborhood: Coney Island
route_types:
- date-night
- easy-stop
- foodie
best_time:
- dinner
- evening
- late-afternoon
- lunch
vibes:
- tasty
best_for:
- couples
external_link: ''
personal: want-to-go
price: $$
