id: radio-city-music-hall
title:
  en: Radio City Music Hall
  ru: Радио-сити-мьюзик-холл
coords:
  lat: 40.75998
  lng: -73.98002
category:
- landmarks
address: 1260 6th Ave, New York, NY 10020
external_link: ''
personal: to-do
price: $$
