id: nom-wah-tea-parlor
title:
  en: Nom Wah Tea Parlor
  ru: Nom Wah Tea Parlor
coords:
  lat: 40.7144593
  lng: -73.9981968
category:
- food
price: $$
address: 13 Doyers St, New York, NY 10013
external_link: https://www.tiktok.com/t/ZP8gHrW8A
personal: want-to-go
