id: roy-fish-market
title:
  en: Roy Fish Market
  ru: Roy Fish Market
coords:
  lat: 40.7617216
  lng: -73.9601005
category:
- food
price: $$
address: 1138 1st Ave, New York, NY 10065
external_link: https://www.tiktok.com/t/ZP8gH71p4
personal: want-to-go
