id: one-world-trade-center
title:
  en: One World Trade Center
  ru: One World Trade Center
coords:
  lat: 40.7127
  lng: -74.0134
category:
- landmarks
price: $$
address: 285 Fulton St, New York, NY 10007
external_link: ''
personal: visited
