id: one-world-trade-center
title:
  en: One World Trade Center
  ru: One World Trade Center
coords:
  lat: 40.7127
  lng: -74.0134
category:
- landmarks
price: $$
address: 285 Fulton St, New York, NY 10007
borough: Manhattan
neighborhood: Financial District
route_types:
- architecture
- culture
- easy-stop
- touristy
best_time:
- afternoon
- midday
vibes:
- curious
best_for: []
external_link: ''
personal: want-to-go
