id: washington-square-arch
title:
  en: Washington Square Arch
  ru: Арка Вашингтон-сквер
coords:
  lat: 40.73121
  lng: -73.99715
category:
- landmarks
address: Washington Square N, New York, NY 10012
external_link: ''
personal: to-do
price: free
