id: grand-central-terminal
title:
  en: Grand Central Terminal
  ru: Гранд Сентрал
coords:
  lat: 40.7527
  lng: -73.9772
category:
- landmarks
address: 89 E 42nd St, New York, NY 10017
external_link: ''
personal: visited
price: $$
