id: saint-tuesday

title:
  en: Saint Tuesday
  ru: Saint Tuesday

coords:
  lat: 0.0
  lng: 0.0

category:
  - other

tags: []

time: medium
cost: paid
price: ""

transit:
  en: Canal St
  ru: Canal St

address: "77 Walker St, New York, NY 10013"
external_link: "https://www.tiktok.com/t/ZP8gHPCFp"

featured: false
