id: guggenheim-museum
title:
  en: Guggenheim Museum
  ru: Музей Гуггенхайма
coords:
  lat: 40.783
  lng: -73.959
category:
- museums
price: $$
address: 1071 5th Ave, New York, NY 10128
external_link: ''
personal: to-do
