id: brooklyn-bridge
title:
  en: Brooklyn Bridge
  ru: Бруклинский мост
coords:
  lat: 40.7061
  lng: -73.9969
category:
- landmarks
address: Brooklyn Bridge Pedestrian Entrance, New York, NY 10038
external_link: ''
personal: visited
price: $$
