id: ferrane
title:
  en: Ferrane
  ru: Ferrane
coords:
  lat: 40.697722
  lng: -73.993671
category:
- food
tags: []
time: short
cost: paid
price: ''
transit:
  en: Clark St
  ru: Clark St
address: 57 Clark St, Brooklyn, NY 11201
external_link: https://www.tiktok.com/t/ZP8gHk4uy
featured: false
