id: laduree-soho
title:
  en: Ladurée SoHo
  ru: Ladurée SoHo
coords:
  lat: 40.7243189
  lng: -74.0024359
category:
- food
price: $$
address: 398 W Broadway, New York, NY 10012
external_link: https://www.tiktok.com/t/ZP8gHdHAu
personal: want-to-go
