id: cafe-2by2
title:
  en: Cafe 2by2
  ru: Cafe 2by2
coords:
  lat: 0.0
  lng: 0.0
category:
- food
tags: []
time: short
cost: paid
price: ''
transit:
  en: Astor Pl / 8 St-NYU
  ru: Astor Pl / 8 St-NYU
address: 84 E 10th St 2nd FL, New York, NY 10003
external_link: https://www.tiktok.com/t/ZP8gHRw9k
featured: false
personal: want-to-go
