id: cafe-2by2
title:
  en: Cafe 2by2
  ru: Cafe 2by2
coords:
  lat: 40.730861
  lng: -73.989922
category:
- food
price: $$
address: 84 E 10th St 2nd FL, New York, NY 10003
external_link: https://www.tiktok.com/t/ZP8gHRw9k
personal: want-to-go
