id: governors-island
title:
  en: Governors Island
  ru: Говернорс-Айленд
coords:
  lat: 40.6895
  lng: -74.0168
category:
- parks
address: Governors Island Ferry Terminal, New York, NY 10004
external_link: ''
personal: to-do
price: $$
