id: pavlo-mochi
title:
  en: Pavlo Mochi
  ru: Pavlo Mochi
coords:
  lat: 40.7282807
  lng: -73.9786656
category:
- food
price: $$
address: 199 Avenue B, New York, NY 10009
external_link: https://www.tiktok.com/t/ZP8gHvweN
personal: to-do
