id: brooklyn-museum
title:
  en: Brooklyn Museum
  ru: Бруклинский музей
coords:
  lat: 40.6712
  lng: -73.9636
category:
- museums
price: $$
address: 200 Eastern Pkwy, Brooklyn, NY 11238
external_link: ''
personal: to-do
