id: rockefeller-center
title:
  en: Rockefeller Center
  ru: Рокфеллер-центр
coords:
  lat: 40.7587
  lng: -73.9787
category:
- landmarks
address: 45 Rockefeller Plaza, New York, NY 10111
external_link: ''
personal: to-do
price: $$
