id: unisphere
title:
  en: Unisphere
  ru: Unisphere
coords:
  lat: 40.7464
  lng: -73.8458
category:
- landmarks
address: Flushing Meadows Corona Park, Queens, NY 11368
external_link: ''
personal: to-do
price: $$
