id: fu-zhou-wei-zhong-wei-jia-xiang-feng-wei
title:
  en: Fu Zhou Wei Zhong Wei Jia Xiang Feng Wei
  ru: Fu Zhou Wei Zhong Wei Jia Xiang Feng Wei
coords:
  lat: 0.0
  lng: 0.0
category:
- food
tags: []
time: medium
cost: paid
price: ''
transit:
  en: East Broadway
  ru: East Broadway
address: 88 E Broadway, New York, NY 10002
external_link: https://www.tiktok.com/t/ZP8gHmxPC
featured: false
personal: want-to-go
