id: fu-zhou-wei-zhong-wei-jia-xiang-feng-wei
title:
  en: Fu Zhou Wei Zhong Wei Jia Xiang Feng Wei
  ru: Fu Zhou Wei Zhong Wei Jia Xiang Feng Wei
coords:
  lat: 40.714009
  lng: -73.994395
category:
- food
price: $$
address: 88 E Broadway, New York, NY 10002
external_link: https://www.tiktok.com/t/ZP8gHmxPC
personal: want-to-go
