id: madison-square-garden
title:
  en: Madison Square Garden
  ru: Мэдисон-сквер-гарден
coords:
  lat: 40.7505
  lng: -73.9934
category:
- landmarks
address: 4 Pennsylvania Plaza, New York, NY 10001
external_link: ''
personal: to-do
price: $$
