id: madison-square-garden
title:
  en: Madison Square Garden
  ru: Мэдисон-сквер-гарден
coords:
  lat: 40.7505
  lng: -73.9934
category:
- landmarks
address: 4 Pennsylvania Plaza, New York, NY 10001
borough: Manhattan
neighborhood: Chelsea
route_types:
- architecture
- culture
- easy-stop
- touristy
best_time:
- afternoon
- midday
vibes:
- curious
best_for: []
external_link: ''
personal: want-to-go
price: $$
