id: chrysler-building
title:
  en: Chrysler Building
  ru: Крайслер-билдинг
coords:
  lat: 40.7516
  lng: -73.9755
category:
- landmarks
address: 405 Lexington Ave, New York, NY 10174
external_link: ''
personal: to-do
price: $$
