id: top-of-the-rock
title:
  en: Top of the Rock
  ru: Top of the Rock
coords:
  lat: 40.7591
  lng: -73.97936
category:
- viewpoints
address: 30 Rockefeller Plaza, New York, NY 10112
external_link: ''
personal: to-do
price: $$
