id: mala-panda
title:
  en: Mala Panda
  ru: Mala Panda
coords:
  lat: 40.7458049
  lng: -73.9913459
category:
- food
price: $$
address: 105 W 27th St, New York, NY 10001
external_link: https://www.tiktok.com/t/ZP8gH41WH
personal: want-to-go
