id: hanamizuki-cafe
title:
  en: Hanamizuki Cafe
  ru: Hanamizuki Cafe
coords:
  lat: 40.7475381
  lng: -73.9916018
category:
- food
price: $$
address: 143 W 29th St, New York, NY 10001
external_link: https://www.tiktok.com/t/ZP8gH6P7f
personal: want-to-go
