id: birds-jazz
title:
  en: Birds
  ru: Birds
coords:
  lat: 40.7288306
  lng: -74.0048718
category:
- other
tags: []
time: medium
cost: paid
price: ''
transit:
  en: Houston St / Christopher St
  ru: Houston St / Christopher St
address: 64 Downing St, New York, NY 10014
external_link: https://www.tiktok.com/t/ZP8gHr1Wn
featured: false
personal: want-to-go
