id: jiang-nan-flushing
title:
  en: Jiang Nan
  ru: Jiang Nan
coords:
  lat: 0.0
  lng: 0.0
category:
  - food
tags: []
time: medium
cost: paid
price: ""
transit:
  en: Flushing-Main St
  ru: Flushing-Main St
address: 133-42 39th Ave STE 101, Flushing, NY 11354
external_link: https://www.tiktok.com/t/ZP8gHbCNY
featured: false
personal: want-to-go
