id: jiang-nan-flushing
title:
  en: Jiang Nan
  ru: Jiang Nan
coords:
  lat: 40.635353
  lng: -74.035395
category:
- food
price: $$
address: 133-42 39th Ave STE 101, Flushing, NY 11354
external_link: https://www.tiktok.com/t/ZP8gHbCNY
personal: to-do
