id: davelle
title:
  en: Davelle
  ru: Davelle
coords:
  lat: 40.7184628
  lng: -73.9860923
category:
- food
price: $$
address: 102 Suffolk St, New York, NY 10002
external_link: https://www.tiktok.com/t/ZP8gHtnVu
personal: want-to-go
