id: ozakaya
title:
  en: Ozakaya
  ru: Ozakaya
coords:
  lat: 40.6780491
  lng: -73.9684471
category:
- food
price: $$
address: 635 Vanderbilt Ave, Brooklyn, NY 11238
external_link: https://www.tiktok.com/t/ZP8gHvpq3
personal: to-do
