id: ozakaya
title:
  en: Ozakaya
  ru: Ozakaya
coords:
  lat: 40.6780491
  lng: -73.9684471
category:
- food
tags: []
time: medium
cost: paid
price: pricey
transit:
  en: Atlantic Terminal / Clinton-Washington Avs
  ru: Atlantic Terminal / Clinton-Washington Avs
address: 635 Vanderbilt Ave, Brooklyn, NY 11238
external_link: https://www.tiktok.com/t/ZP8gHvpq3
featured: false
personal: want-to-go
