id: chelsea-market
title:
  en: Chelsea Market
  ru: Челси Маркет
coords:
  lat: 40.7423
  lng: -74.006
category:
- food
address: 75 9th Ave, New York, NY 10011
external_link: ''
personal: visited
price: $$
