id: chelsea-market
title:
  en: Chelsea Market
  ru: Челси Маркет
coords:
  lat: 40.7423
  lng: -74.006
category:
- food
address: 75 9th Ave, New York, NY 10011
borough: Manhattan
neighborhood: Chelsea
route_types:
- date-night
- easy-stop
- foodie
- shopping
best_time:
- dinner
- evening
- late-afternoon
- lunch
vibes:
- tasty
best_for:
- couples
external_link: ''
personal: want-to-go
price: $$
