id: mercer-labs
title:
  en: Mercer Labs
  ru: Mercer Labs
coords: {lat: 40.7103, lng: -74.0087}
category: [museums]
time: medium
cost: paid
price: ~0+
transit:
  en: Fulton St / World Trade Center
  ru: Fulton St / World Trade Center
