id: times-square
title:
  en: Times Square
  ru: Таймс-сквер
coords: {lat: 40.7580, lng: -73.9855}
category: [landmarks]
time: short
cost: free
transit:
  en: Times Sq–42 St
  ru: Times Sq–42 St
address: "Times Square, New York, NY 10036"
