id: bakery-je-taime
title:
  en: Bakery Je T’Aime
  ru: Bakery Je T’Aime
coords:
  lat: 40.680853
  lng: -73.937511
category:
- food
price: $$
address: 471 Marcus Garvey Blvd, Brooklyn, NY 11216
external_link: https://www.tiktok.com/t/ZP8gHaMvJ
personal: want-to-go
