id: bakery-je-taime
title:
  en: Bakery Je T’Aime
  ru: Bakery Je T’Aime
coords:
  lat: 0.0
  lng: 0.0
category:
- food
tags: []
time: short
cost: paid
price: ''
transit:
  en: Bedford-Nostrand Avs / Marcus Garvey Blvd area
  ru: район Bedford-Nostrand Avs / Marcus Garvey Blvd
address: 471 Marcus Garvey Blvd, Brooklyn, NY 11216
external_link: https://www.tiktok.com/t/ZP8gHaMvJ
featured: false
personal: want-to-go
