id: coney-island
title:
  en: Coney Island
  ru: Кони-Айленд
coords:
  lat: 40.5749
  lng: -73.985
category:
- landmarks
address: Surf Ave & Stillwell Ave, Brooklyn, NY 11224
external_link: ''
personal: to-do
price: $$
