id: skirt-steak
title:
  en: Skirt Steak
  ru: Skirt Steak
coords:
  lat: 40.746807
  lng: -73.990083
category:
  - food
personal: highly-recommend

price: $$
address: 835 6th Ave, New York, NY 10001
external_link: https://www.tiktok.com/t/ZP8gHkxCm
