id: bethesda-fountain
title:
  en: Bethesda Fountain
  ru: Фонтан Bethesda
coords:
  lat: 40.774
  lng: -73.97
category:
- parks
address: Central Park, Terrace Dr, New York, NY 10021
external_link: ''
personal: visited
price: $$
