id: saint-tuesday
title:
  en: Saint Tuesday
  ru: Saint Tuesday
coords:
  lat: 40.718348
  lng: -74.00214
category:
- other
price: $$
address: 77 Walker St, New York, NY 10013
external_link: https://www.tiktok.com/t/ZP8gHPCFp
personal: to-do
