id: this-bowl
title:
  en: This Bowl
  ru: This Bowl
coords:
  lat: 40.7439412
  lng: -73.988134
category:
- food
price: $$
address: 230 5th Ave, New York, NY 10001
external_link: https://www.tiktok.com/t/ZP8gHPF2g
personal: to-do
