id: gyu-ichiro
title:
  en: GYU Ichiro
  ru: GYU Ichiro
coords:
  lat: 40.7186613
  lng: -73.9943363
category:
- food
price: $$
address: 135 Bowery, New York, NY 10002
external_link: https://www.tiktok.com/t/ZP8gHcgxC
personal: want-to-go
