id: hamido-seafood
title:
  en: Hamido Seafood
  ru: Hamido Seafood
coords:
  lat: 40.775650
  lng: -73.909508
category:
  - food
price: $$
address: 31-29 Ditmars Blvd, Astoria, NY 11105
external_link: https://www.tiktok.com/t/ZP8gH4D1u
personal: want-to-go
