id: champagne-problems
title:
  en: Champagne Problems
  ru: Champagne Problems
coords:
  lat: 40.721237
  lng: -73.9932953
category:
- other
tags: []
time: medium
cost: paid
price: ''
transit:
  en: Bowery / Grand St
  ru: Bowery / Grand St
address: 207 Bowery, New York, NY 10002
external_link: https://www.tiktok.com/t/ZP8gHGcoY
featured: false
personal: want-to-go
