id: champagne-problems
title:
  en: Champagne Problems
  ru: Champagne Problems
coords:
  lat: 40.721237
  lng: -73.9932953
category:
- other
price: $$
address: 207 Bowery, New York, NY 10002
external_link: https://www.tiktok.com/t/ZP8gHGcoY
personal: want-to-go
