id: ole-and-steen
title:
  en: Ole & Steen
  ru: Ole & Steen
coords:
  lat: 40.7417
  lng: -73.9894
category:
- food
address: 80 W 40th St, New York, NY 10018
borough: Manhattan
neighborhood: Flatiron / NoMad
route_types:
- date-night
- easy-stop
- foodie
best_time:
- dinner
- evening
- late-afternoon
- lunch
vibes:
- tasty
best_for:
- couples
external_link: ''
personal: want-to-go
price: $$
