id: ole-and-steen
title:
  en: Ole & Steen
  ru: Ole & Steen
coords:
  lat: 40.7417
  lng: -73.9894
category:
- food
address: 80 W 40th St, New York, NY 10018
external_link: ''
personal: to-do
price: $$
