id: tortelli
title:
  en: Tortelli
  ru: Tortelli
coords:
  lat: 40.6822688
  lng: -73.9931502
category:
- food
tags: []
time: medium
cost: paid
price: ''
transit:
  en: Carroll St / Red Hook edge
  ru: Carroll St / ближе к Red Hook
address: 359 Sackett St, Brooklyn, NY 11231
external_link: https://www.tiktok.com/t/ZP8gHQ8mt
featured: false
personal: want-to-go
