id: tortelli
title:
  en: Tortelli
  ru: Tortelli
coords:
  lat: 40.6822688
  lng: -73.9931502
category:
- food
price: $$
address: 359 Sackett St, Brooklyn, NY 11231
external_link: https://www.tiktok.com/t/ZP8gHQ8mt
personal: want-to-go
