id: cathedral-of-st-john-the-divine
title:
  en: Cathedral of St. John the Divine
  ru: Собор Святого Иоанна Богослова
coords:
  lat: 40.8038
  lng: -73.9619
category:
- landmarks
address: 1047 Amsterdam Ave, New York, NY 10025
external_link: ''
personal: visited
price: $$
