id: mms-store
title:
  en: M&M's Store
  ru: Магазин M&M's
coords:
  lat: 40.7587
  lng: -73.9851
category:
- other
address: 1600 Broadway, New York, NY 10019
external_link: ''
personal: visited
price: $$
