id: the-cloisters
title:
  en: The Met Cloisters
  ru: Мет Клойстерс
coords:
  lat: 40.86486
  lng: -73.93173
category:
- museums
address: 99 Margaret Corbin Dr, New York, NY 10040
external_link: ''
personal: to-do
price: $$
