id: times-square
title:
  en: Times Square
  ru: Таймс-сквер
coords:
  lat: 40.758
  lng: -73.9855
category:
- landmarks
address: Times Square, New York, NY 10036
external_link: ''
personal: to-do
price: $$
