id: little-island
title:
  en: Little Island
  ru: Little Island
coords:
  lat: 40.742
  lng: -74.016
category:
- parks
personal: to-do
price: $$
address: Pier 55, Hudson River Greenway, New York, NY 10014
external_link: ''
