id: nonnas-of-the-world
title:
  en: Nonna's of the World
  ru: Nonna's of the World
coords:
  lat: 40.642
  lng: -74.07729
category:
- food
address: 27 Hyatt St, Staten Island, NY 10301
external_link: ''
personal: to-do
price: $$
