id: the-edge
title:
  en: The Edge
  ru: Edge смотровая
coords:
  lat: 40.7539
  lng: -74.0027
category:
- viewpoints
price: $$
address: 30 Hudson Yards, New York, NY 10001
external_link: ''
personal: visited
