id: met-museum
title:
  en: MET Museum
  ru: Метрополитен музей
coords:
  lat: 40.7794
  lng: -73.9632
category:
- museums
price: $$
address: 1000 5th Ave, New York, NY 10028
external_link: ''
personal: to-do
