id: governors-island
title:
  en: Governors Island
  ru: Говернорс-Айленд
coords: {lat: 40.6895, lng: -74.0168}
category: [parks]
time: full
cost: free
transit:
  en: Ferry from Manhattan/Brooklyn
  ru: Паром
