id: bryant-park
title:
  en: Bryant Park
  ru: Брайант-парк
coords:
  lat: 40.7536
  lng: -73.9832
category:
- parks
address: Bryant Park, New York, NY 10018
external_link: ''
personal: to-do
price: $$
