id: the-vessel
title:
  en: The Vessel
  ru: Вессел
coords:
  lat: 40.7538
  lng: -74.0021
category:
- landmarks
address: 20 Hudson Yards, New York, NY 10001
external_link: ''
personal: to-do
price: $$
