id: casa-adela
title:
  en: Casa Adela
  ru: Casa Adela
coords:
  lat: 40.722596
  lng: -73.9796301
category:
- food
price: $$
address: 66 Loisaida Ave, New York, NY 10009
external_link: https://www.tiktok.com/t/ZP8gHyVRN
personal: to-do
