id: yubu
title:
  en: Yubu
  ru: Yubu
coords:
  lat: 40.7226458
  lng: -74.0039528
category:
- food
price: $$
address: 46 Grand St, New York, NY 10013
external_link: https://www.tiktok.com/t/ZP8gHMkFT
personal: to-do
