id: yubu
title:
  en: Yubu
  ru: Yubu
coords:
  lat: 0.0
  lng: 0.0
category:
- food
tags: []
time: short
cost: paid
price: ''
transit:
  en: Canal St
  ru: Canal St
address: 46 Grand St, New York, NY 10013
external_link: https://www.tiktok.com/t/ZP8gHMkFT
featured: false
personal: want-to-go
