id: luckin-coffee-6th-ave
title:
  en: Luckin Coffee
  ru: Luckin Coffee
coords:
  lat: 40.7456025
  lng: -73.9904181
category:
- food
tags: []
time: short
cost: paid
price: ''
transit:
  en: 28 St / 34 St
  ru: 28 St / 34 St
address: 800 6th Ave, New York, NY 10001
external_link: https://www.tiktok.com/t/ZP8gHNV8U
featured: false
