id: din-soup-dumplings
title:
  en: Din Soup Dumplings
  ru: Din Soup Dumplings
coords:
  lat: 40.694152
  lng: -73.992819
category:
- food
price: $$
address: 162 Montague St Fl 2, Brooklyn, NY 11201
external_link: https://www.tiktok.com/t/ZP8gHNPXb
personal: want-to-go
