id: tashkent-supermarket
title:
  en: Tashkent Supermarket
  ru: Супермаркет Ташкент
coords: {lat: 40.7312, lng: -73.9952}
category: [food]
time: short
cost: paid
transit:
  en: W 4 St
  ru: W 4 St
address: "378 6th Ave, New York, NY 10011"
