id: penn-station
title:
  en: Penn Station
  ru: Пенн-стейшн
coords:
  lat: 40.7506
  lng: -73.9935
category:
- other
address: 8th Ave & W 31st St, New York, NY 10001
external_link: ''
personal: visited
price: $$
