id: lego-store-5th-ave
title:
  en: LEGO Store (5th Ave)
  ru: LEGO Store
coords:
  lat: 40.7605
  lng: -73.975
category:
- other
address: 636 5th Ave, New York, NY 10020
borough: Manhattan
neighborhood: Midtown East
route_types:
- budget-friendly
- easy-stop
- shopping
best_time: []
vibes: []
best_for:
- budget
external_link: ''
personal: want-to-go
price: $$
