id: conwell-coffee-hall
title:
  en: Conwell Coffee Hall
  ru: Conwell Coffee Hall
coords:
  lat: 40.7075
  lng: -74.0109
category:
- food
address: 6 Hanover St, New York, NY 10005
external_link: ''
personal: to-do
price: $$
