id: ellis-island
title:
  en: Ellis Island
  ru: Эллис-Айленд
coords: {lat: 40.6995, lng: -74.0396}
category: [museums]
time: medium
cost: paid
transit:
  en: Same ferry as Statue of Liberty
  ru: Тот же паром
