id: jongro-bbq-market
title:
  en: Jongro BBQ Market
  ru: Jongro BBQ Market
coords:
  lat: 40.7481659
  lng: -73.9873042
category:
- food
price: $$
address: 39 W 32nd St 1st Fl, New York, NY 10001
external_link: https://www.tiktok.com/t/ZP8gHRqMM
personal: to-do
