id: baires-grill
title:
  en: Baires Grill
  ru: Baires Grill
coords:
  lat: 40.7627443
  lng: -73.9878936
category:
- food
price: $$
address: 350 W 50th St, New York, NY 10019
external_link: https://www.tiktok.com/t/ZP8gHTnFd
personal: to-do
