id: baires-grill
title:
  en: Baires Grill
  ru: Baires Grill
coords:
  lat: 40.7627443
  lng: -73.9878936
category:
- food
tags: []
time: medium
cost: paid
price: ''
transit:
  en: 50 St
  ru: 50 St
address: 350 W 50th St, New York, NY 10019
external_link: https://www.tiktok.com/t/ZP8gHTnFd
featured: false
personal: want-to-go
