id: the-office-of-mr-motto
title:
  en: The Office of Mr. Motto
  ru: The Office of Mr. Motto
coords:
  lat: 40.7271325
  lng: -73.9841985
category:
- food
tags: []
time: medium
cost: paid
price: $100+
transit:
  en: Astor Pl / 2 Av
  ru: Astor Pl / 2 Av
address: 120A St Marks Pl, New York, NY 10009
external_link: https://www.tiktok.com/t/ZP8gHgceb
featured: false
personal: want-to-go
