id: new-yorker-hotel
title:
  en: The New Yorker Hotel
  ru: Отель The New Yorker
coords:
  lat: 40.7528
  lng: -73.9935
category:
- landmarks
address: 481 8th Ave, New York, NY 10001
external_link: ''
personal: visited
price: $$
