id: ellis-island
title:
  en: Ellis Island
  ru: Эллис-Айленд
coords:
  lat: 40.6995
  lng: -74.0396
category:
- museums
address: Ellis Island, New York, NY 10004
external_link: ''
personal: visited
price: $$
