id: new-kim-tuong
title:
  en: New Kim Tuong
  ru: New Kim Tuong
coords:
  lat: 40.71745
  lng: -73.9943952
category:
- food
price: $$
address: 83 Chrystie St, New York, NY 10002
external_link: https://www.tiktok.com/t/ZP8gHjkrX
personal: to-do
