id: one-world-observatory
title:
  en: One World Observatory
  ru: One World Observatory
coords:
  lat: 40.71301
  lng: -74.01317
category:
- viewpoints
address: 117 West St, New York, NY 10007
external_link: ''
personal: to-do
price: $$
