id: intrepid-museum
title:
  en: Intrepid Museum
  ru: Музей Intrepid
coords:
  lat: 40.7645
  lng: -73.9996
category:
- museums
price: $$
address: Pier 86, W 46th St, New York, NY 10036
external_link: ''
personal: to-do
