id: nonnas-of-the-world
title:
  en: Nonna's of the World
  ru: Nonna's of the World
coords: {lat: 40.7198, lng: -73.9906}
category: [food]
time: medium
cost: paid
transit:
  en: Delancey St / Essex St
  ru: Delancey St / Essex St
