id: wall-street-bull
title:
  en: Wall Street Bull
  ru: Бык на Уолл-стрит
coords:
  lat: 40.7055
  lng: -74.0134
category:
- landmarks
address: Bowling Green, New York, NY 10004
external_link: ''
personal: to-do
price: $$
