id: smashy-burger-union-square
title:
  en: Smashy Burger
  ru: Smashy Burger
coords:
  lat: 40.7361989
  lng: -73.98901
category:
- food
price: $$
address: 42 Union Sq E, New York, NY 10003
external_link: https://www.tiktok.com/t/ZP8gHspcy
personal: to-do
