id: smashy-burger-union-square
title:
  en: Smashy Burger
  ru: Smashy Burger
coords:
  lat: 40.7361989
  lng: -73.98901
category:
- food
tags: []
time: short
cost: paid
price: $5 burgers
transit:
  en: 14 St-Union Sq
  ru: 14 St-Union Sq
address: 42 Union Sq E, New York, NY 10003
external_link: https://www.tiktok.com/t/ZP8gHspcy
featured: false
personal: want-to-go
