id: gan-hoo-bbq
title:
  en: Gan Hoo BBQ
  ru: Gan Hoo BBQ
coords:
  lat: 40.7451081
  lng: -73.9842044
category:
- food
price: $$
address: 29 E 30th St, New York, NY 10016
external_link: https://www.tiktok.com/t/ZP8gHkcvp
personal: to-do
