id: tashkent-supermarket
title:
  en: Tashkent Supermarket
  ru: Супермаркет Ташкент
coords:
  lat: 40.7312
  lng: -73.9952
category:
- food
address: 378 6th Ave, New York, NY 10011
external_link: ''
personal: to-do
price: $$
