id: nyse
title:
  en: New York Stock Exchange
  ru: Нью-Йоркская фондовая биржа
coords:
  lat: 40.7069
  lng: -74.0113
category:
- landmarks
address: 11 Wall St, New York, NY 10005
external_link: ''
personal: to-do
price: $$
