id: oculus
title:
  en: Oculus
  ru: Окулус
coords:
  lat: 40.7115
  lng: -74.0113
category:
- landmarks
personal: been-not-impressed
time: short
cost: free
transit:
  en: World Trade Center
  ru: World Trade Center
address: 185 Greenwich St, New York, NY 10007
borough: Manhattan
neighborhood: Financial District
route_types:
- architecture
- budget-friendly
- culture
- easy-stop
- touristy
best_time:
- afternoon
- midday
vibes:
- curious
best_for:
- budget
external_link: ""
