id: joes-home-of-soup-dumplings
title:
  en: Joe's Home of Soup Dumplings
  ru: Joe's Home of Soup Dumplings
coords:
  lat: 40.7153
  lng: -73.9975
category:
- food
address: 24 W 56th St, New York, NY 10019
external_link: ''
personal: visited
price: $$
