id: annapurna-thakali-kitchen
title:
  en: Annapurna Thakali Kitchen
  ru: Annapurna Thakali Kitchen
coords:
  lat: 40.746610
  lng: -73.893265
category:
- food
price: $$
address: 72-24 Roosevelt Ave, Jackson Heights, NY 11372
external_link: https://www.tiktok.com/t/ZP8gHmvYG
personal: want-to-go
