id: hanamizuki-cafe
title:
  en: Hanamizuki Cafe
  ru: Hanamizuki Cafe
coords:
  lat: 40.7475381
  lng: -73.9916018
category:
- food
tags: []
time: short
cost: paid
price: ''
transit:
  en: 28 St / Penn Station area
  ru: 28 St / район Penn Station
address: 143 W 29th St, New York, NY 10001
external_link: https://www.tiktok.com/t/ZP8gH6P7f
featured: false
