id: sushi-counter
title:
  en: Sushi Counter
  ru: Sushi Counter
coords:
  lat: 40.73337
  lng: -74.005613
category:
- food
price: $$
address: 119 Christopher St, New York, NY 10014
external_link: https://www.tiktok.com/t/ZP8gHUcGF
personal: to-do
