id: gan-hoo-bbq

title:
  en: Gan Hoo BBQ
  ru: Gan Hoo BBQ

coords:
  lat: 0.0
  lng: 0.0

category:
  - food

tags: []

time: medium
cost: paid
price: ""

transit:
  en: 28 St / 33 St
  ru: 28 St / 33 St

address: "29 E 30th St, New York, NY 10016"
external_link: "https://www.tiktok.com/t/ZP8gHkcvp"

featured: false
