id: lincoln-center
title:
  en: Lincoln Center
  ru: Линкольн-центр
coords:
  lat: 40.7725
  lng: -73.9835
category:
- landmarks
address: Lincoln Center Plaza, New York, NY 10023
external_link: ''
personal: visited
price: $$
