id: gantry-plaza-state-park
title:
  en: Gantry Plaza State Park
  ru: Gantry Plaza State Park
coords:
  lat: 40.74794
  lng: -73.95956
category:
- viewpoints
address: 4-44 47th Rd, Long Island City, NY 11101
external_link: ''
personal: to-do
price: free
