id: chinatown
title:
  en: Chinatown
  ru: Чайнатаун
coords:
  lat: 40.7158
  lng: -73.997
category:
- landmarks
address: Canal St & Mott St, New York, NY 10013
external_link: ''
personal: to-do
price: $$
