id: alimama-tea
title:
  en: Alimama Tea
  ru: Alimama Tea
coords:
  lat: 40.7157707
  lng: -73.9991388
category:
- food
price: $$
address: 89A Bayard St, New York, NY 10013
external_link: https://www.tiktok.com/t/ZP8gHFrEV
personal: want-to-go
