id: broadway-theater-district
title:
  en: Broadway Theater District
  ru: Театральный район Бродвея
coords:
  lat: 40.75901
  lng: -73.98447
category:
- other
address: Broadway & W 45th St, New York, NY 10036
external_link: ''
personal: to-do
price: $$
