id: larina
title:
  en: Larina
  ru: Larina
coords:
  lat: 40.6933068
  lng: -73.9704183
category:
- food
price: $$
address: 387 Myrtle Ave, Brooklyn, NY 11205
external_link: https://www.tiktok.com/t/ZP8gHKMEW
personal: to-do
