id: larina
title:
  en: Larina
  ru: Larina
coords:
  lat: 40.6933068
  lng: -73.9704183
category:
- food
tags: []
time: medium
cost: paid
price: ''
transit:
  en: Myrtle-Willoughby Avs / DeKalb Ave area
  ru: Myrtle-Willoughby Avs / район DeKalb Ave
address: 387 Myrtle Ave, Brooklyn, NY 11205
external_link: https://www.tiktok.com/t/ZP8gHKMEW
featured: false
personal: want-to-go
