id: piscator
title:
  en: Piscator
  ru: Piscator
coords:
  lat: 40.733463
  lng: -73.9550346
category:
- food
price: $$
address: 1011 Manhattan Ave, Brooklyn, NY 11222
external_link: https://www.tiktok.com/t/ZP8gHqrKc
personal: want-to-go
