id: summit-one-vanderbilt
title:
  en: SUMMIT One Vanderbilt
  ru: SUMMIT One Vanderbilt
coords:
  lat: 40.75399
  lng: -73.97825
category:
- viewpoints
address: 45 E 42nd St, New York, NY 10017
external_link: ''
personal: to-do
price: $$
