id: washington-square-park
title:
  en: Washington Square Park
  ru: Вашингтон-сквер-парк
coords:
  lat: 40.7308
  lng: -73.9973
category:
- parks
address: Washington Square, New York, NY 10012
external_link: ''
personal: visited
price: $$
