id: sushi-counter
title:
  en: Sushi Counter
  ru: Sushi Counter
coords:
  lat: 40.73337
  lng: -74.005613
category:
- food
tags: []
time: short
cost: paid
price: $12 / 3 hand rolls
transit:
  en: Christopher St-Sheridan Sq
  ru: Christopher St-Sheridan Sq
address: 119 Christopher St, New York, NY 10014
external_link: https://www.tiktok.com/t/ZP8gHUcGF
featured: false
