id: harry-potter-store
title:
  en: Harry Potter Store
  ru: Магазин Гарри Поттера
coords:
  lat: 40.742
  lng: -73.989
category:
- other
address: 935 Broadway, New York, NY 10010
external_link: ''
personal: to-do
price: $$
