id: luckin-coffee-6th-ave
title:
  en: Luckin Coffee
  ru: Luckin Coffee
coords:
  lat: 40.7456025
  lng: -73.9904181
category:
- food
price: $$
address: 800 6th Ave, New York, NY 10001
external_link: https://www.tiktok.com/t/ZP8gHNV8U
personal: want-to-go
