id: whitney-museum
title:
  en: Whitney Museum
  ru: Музей Whitney
coords:
  lat: 40.7396
  lng: -74.0089
category:
- museums
price: $$
address: 99 Gansevoort St, New York, NY 10014
external_link: ''
personal: to-do
