id: ume
title:
  en: Ume
  ru: Ume
coords:
  lat: 40.7165079
  lng: -73.9654572
category:
- food
tags: []
time: medium
cost: paid
price: $80 pp
transit:
  en: Bedford Ave / Williamsburg waterfront
  ru: Bedford Ave / набережная Williamsburg
address: 237 Kent Ave, Brooklyn, NY 11249
external_link: https://www.tiktok.com/t/ZP8gHGbog
featured: false
personal: want-to-go
