id: ume
title:
  en: Ume
  ru: Ume
coords:
  lat: 40.7165079
  lng: -73.9654572
category:
- food
price: $$
address: 237 Kent Ave, Brooklyn, NY 11249
external_link: https://www.tiktok.com/t/ZP8gHGbog
personal: to-do
