id: manhattan-bridge-view
title:
  en: Manhattan Bridge View
  ru: Вид на Манхэттенский мост
coords:
  lat: 40.7033
  lng: -73.9887
category:
- viewpoints
address: Washington St & Front St, Brooklyn, NY 11201
external_link: ''
personal: visited
price: $$
