id: rooftop-230-fifth
title:
  en: 230 Fifth Rooftop Bar
  ru: Рooftop-бар 230 Fifth
coords:
  lat: 40.7442
  lng: -73.9889
category:
- food
address: 230 5th Ave, New York, NY 10001
external_link: ''
personal: to-do
price: $$
