id: sendo
title:
  en: Sendo
  ru: Sendo
coords:
  lat: 0.0
  lng: 0.0
category:
  - food
tags: []
time: medium
cost: paid
price: ""
transit:
  en: 28 St / Herald Sq
  ru: 28 St / Herald Sq
address: 876 6th Ave 2nd Floor, New York, NY 10001
external_link: https://www.tiktok.com/t/ZP8gHHAtG
featured: false
personal: want-to-go
