id: sendo
title:
  en: Sendo
  ru: Sendo
coords:
  lat: 40.747963
  lng: -73.988992
category:
  - food
price: $$
address: 876 6th Ave 2nd Floor, New York, NY 10001
external_link: https://www.tiktok.com/t/ZP8gHHAtG
personal: want-to-go
