id: ichiran-ramen-midtown
title:
  en: Ichiran Ramen
  ru: Ichiran Ramen
coords:
  lat: 40.7600629
  lng: -73.9832897
category:
- food
price: $$
address: 152 W 49th St, New York, NY 10020
external_link: https://www.tiktok.com/t/ZP8gHfRJU
personal: want-to-go
