id: federal-reserve
title:
  en: Federal Reserve Bank
  ru: Федеральный резерв
coords:
  lat: 40.7074
  lng: -74.0103
category:
- landmarks
time: short
cost: free
transit:
  en: Wall St
  ru: Wall St
address: 33 Liberty St, New York, NY 10045
borough: Manhattan
neighborhood: Financial District
route_types:
- architecture
- budget-friendly
- culture
- easy-stop
- history
- touristy
best_time:
- afternoon
- midday
vibes:
- curious
best_for:
- budget
external_link: ""
