id: ny-public-library
title:
  en: NY Public Library
  ru: Публичная библиотека Нью-Йорка
coords:
  lat: 40.7532
  lng: -73.9822
category:
- landmarks
address: 476 5th Ave, New York, NY 10018
external_link: ''
personal: visited
price: $$
