id: socrates-sculpture-park
title:
  en: Socrates Sculpture Park
  ru: Парк скульптур Сократа
coords:
  lat: 40.7678
  lng: -73.9368
category:
- hidden-gems
address: 32-01 Vernon Blvd, Queens, NY 11106
external_link: ''
personal: to-do
price: $$
