id: brooklyn-heights-promenade
title:
  en: Brooklyn Heights Promenade
  ru: Променад Brooklyn Heights
coords:
  lat: 40.69856
  lng: -73.99672
category:
- viewpoints
address: Montague St &, Pierrepont Pl, Brooklyn, NY 11201
external_link: ''
personal: to-do
price: free
