id: chirokuro
title:
  en: Chirokuro
  ru: Chirokuro
coords:
  lat: 40.727627
  lng: -73.988718
category:
- food
price: $$
address: 103 2nd Ave, New York, NY 10003
external_link: https://www.tiktok.com/t/ZP8gHgP1u
personal: to-do
