id: chirokuro
title:
  en: Chirokuro
  ru: Chirokuro
coords:
  lat: 40.727627
  lng: -73.988718
category:
- food
tags: []
time: medium
cost: paid
price: ''
transit:
  en: Astor Pl / 8 St-NYU
  ru: Astor Pl / 8 St-NYU
address: 103 2nd Ave, New York, NY 10003
external_link: https://www.tiktok.com/t/ZP8gHgP1u
featured: false
personal: want-to-go
