id: hudson-yards
title:
  en: Hudson Yards
  ru: Хадсон Ярдс
coords:
  lat: 40.754
  lng: -74.0027
category:
- landmarks
address: 20 Hudson Yards, New York, NY 10001
external_link: ''
personal: visited
price: $$
