id: louis-vuitton-5th-ave
title:
  en: Louis Vuitton (5th Ave)
  ru: Louis Vuitton на 5-й авеню
coords:
  lat: 40.7607
  lng: -73.975
category:
- other
address: 1 E 57th St, New York, NY 10022
external_link: ''
personal: to-do
price: $$
