id: seaglass-carousel
title:
  en: SeaGlass Carousel
  ru: SeaGlass Carousel
coords:
  lat: 40.7033
  lng: -74.017
category:
- other
address: State St & Battery Pl, New York, NY 10004
external_link: ''
personal: to-do
price: $$
