id: seaglass-carousel
title:
  en: SeaGlass Carousel
  ru: SeaGlass Carousel
coords: {lat: 40.7033, lng: -74.0170}
category: [other]
time: short
cost: paid
transit:
  en: Bowling Green
  ru: Bowling Green
address: "State St & Battery Pl, New York, NY 10004"
