id: alimama-tea
title:
  en: Alimama Tea
  ru: Alimama Tea
coords:
  lat: 40.7157707
  lng: -73.9991388
category:
- food
tags: []
time: short
cost: paid
price: ''
transit:
  en: Canal St
  ru: Canal St
address: 89A Bayard St, New York, NY 10013
external_link: https://www.tiktok.com/t/ZP8gHFrEV
featured: false
