id: lafayette-grand-cafe-bakery

title:
  en: Lafayette Grand Café & Bakery
  ru: Lafayette Grand Café & Bakery

coords:
  lat: 0.0
  lng: 0.0

category:
  - food

tags: []

time: medium
cost: paid
price: ""

transit:
  en: Bleecker St / Broadway-Lafayette
  ru: Bleecker St / Broadway-Lafayette

address: "380 Lafayette St, New York, NY 10003"
external_link: "https://www.tiktok.com/t/ZP8gHmSRS"

featured: false
