id: american-museum-of-natural-history
title:
  en: American Museum of Natural History
  ru: Американский музей естественной истории
coords:
  lat: 40.7813
  lng: -73.9735
category:
- museums
price: $$
address: 200 Central Park W, New York, NY 10024
external_link: ''
personal: visited
