id: american-museum-of-natural-history
title:
  en: American Museum of Natural History
  ru: Американский музей естественной истории
coords:
  lat: 40.7813
  lng: -73.9735
category:
- museums
time: full
cost: paid
price: ~0
transit:
  en: 81 St - Museum of Natural History
  ru: 81 St - Museum of Natural History
address: 200 Central Park W, New York, NY 10024
borough: Manhattan
neighborhood: Upper West Side
route_types:
- anchor-stop
- culture
- rainy-day
best_time:
- afternoon
- midday
vibes:
- curious
best_for: []
external_link: ''
personal: want-to-go
