id: high-line
title:
  en: High Line
  ru: Хай Лайн
coords:
  lat: 40.7479
  lng: -74.0049
category:
- parks
address: Gansevoort St Entrance, New York, NY 10014
external_link: ''
personal: to-do
price: $$
