id: laduree-soho

title:
  en: Ladurée SoHo
  ru: Ladurée SoHo

coords:
  lat: 0.0
  lng: 0.0

category:
  - food

tags: []

time: medium
cost: paid
price: ""

transit:
  en: Prince St / Spring St
  ru: Prince St / Spring St

address: "398 W Broadway, New York, NY 10012"
external_link: "https://www.tiktok.com/t/ZP8gHdHAu"

featured: false
